---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-toml
  - id: debug-statements
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.3
  hooks:
  - id: yamlfmt
    args:
    - --mapping
    - '2'
    - --sequence
    - '2'
    - --offset
    - '0'
    - --width
    - '80'
    - --preserve-quotes
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.35.1
  hooks:
  - id: yamllint
    args: [--format, parsable, --strict, -d, relaxed]
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.9.7'
  hooks:
  - id: ruff-format
  - id: ruff
    args: [--extend-ignore=D1, --fix]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0
  hooks:
  - id: mypy
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.7
  hooks:
  - id: actionlint
    name: actionlint
    description: Runs actionlint to lint GitHub Actions workflow files
