---
resource_types:
- name: ami
  type: docker-image
  source:
    repository: jdub/ami-resource
- name: pulumi
  source:
    repository: mitodl/concourse-pulumi-resource-provisioner
  type: docker-image

resources:
- name: vault-ami
  type: ami
  check_every: 1m
  source:
    region: us-east-1
    filters:
      owner-id: 610119931565
      is-public: false
      state: available
      name: vault-server-*

- icon: github
  name: pulumi_files
  source:
    branch: master
    paths:
    - src/ol_infrastructure/infrastructure/vault
    uri: https://github.com/mitodl/ol-infrastructure
  type: git

- name: pulumi-infra
  source:
  type: pulumi

jobs:
- name: vault-ami-build
  plan:
  - get: vault-ami
  - get: pulumi_files
  - put: pulumi-infra
    inputs:
    - aws_creds
    - pulumi_files
    get_params:
      skip_implicit_get: true
    params:
      action: update
      env_os:
        AWS_DEFAULT_REGION: us-east-1
        PYTHONPATH: /usr/lib/:/tmp/build/put/pulumi_files/src/
      project_name: ol-infrastructure-vault-server
      source_dir: pulumi_files/src/ol_infrastructure/infrastructure/vault
      stack_name: infrastructure.vault.operations.CI
