FROM mitodl/concourse-pulumi-resource
ENV PYTHONUNBUFFERED=1
CMD ["/bin/sh"]

RUN pip install --no-cache-dir boto3 httpx hvac hvac["parser"] parliament pulumi-aws pulumi-fastly pulumi-github pulumi-tls pulumi-vault pulumi_consul pydantic pulumi-mongodbatlas bcrypt
