FROM mitodl/concourse-pulumi-resource@sha256:7f069fcae99d44ea9c53e9a722d81359d572e3b05d48e6876c9e1428e421f78d
ENV PYTHONUNBUFFERED=1
CMD ["/bin/sh"]

RUN apk add --no-cache --update build-base libffi-dev && \
    pip install --no-cache-dir boto3 httpx hvac hvac["parser"] parliament pulumi-aws pulumi-fastly pulumi-github pulumi-tls pulumi-vault pulumi_consul pydantic pulumi-mongodbatlas bcrypt
