FROM python:3.14-slim@sha256:bc389f7dfcb21413e72a28f491985326994795e34d2b86c8ae2f417b4e7818aa
ENV PYTHONUNBUFFERED=1
ENV PATH="${PATH}:/root/.pulumi/bin"
WORKDIR /opt/resource
CMD ["/bin/sh"]

ARG PULUMI_VERSION=3.23.2

RUN apt-get update && apt-get install -y --no-install-recommends curl && \
    curl -fsSL https://get.pulumi.com | sh -s -- --version ${PULUMI_VERSION} && \
    rm -f /root/.pulumi/bin/pulumi-language-dotnet /root/.pulumi/bin/pulumi-language-go /root/.pulumi/bin/pulumi-language-nodejs /root/.pulumi/bin/pulumi-resource-pulumi-nodejs && \
    pip install --no-cache-dir pulumi~=${PULUMI_VERSION} && \
    apt-get purge -y curl && apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

COPY bin/* /opt/resource/
COPY lib/* /opt/resource/lib/
