---
resource_types:
- name: pulumi
  type: docker-image
  source:
    repository: mitodl/concourse-pulumi-resource-provisioner
    tag: latest

resources:
- icon: github
  name: pulumi_files
  source:
    branch: main
    paths:
    - src/ol_infrastructure/applications/sign_and_verify
    uri: https://github.com/mitodl/ol-infrastructure
  type: git
- name: pulumi-thing-doer
  type: pulumi

jobs:
- name: pulumi-stuff-and-things
  plan:
  - get: pulumi_files
    trigger: true
    params:
      depth: 1
  - put: pulumi-thing-doer
    params:
      action: update
      stack_name: applications.sign_and_verify.QA
      project_name: ol-infrastructure-sign-and-verify-application
      source_dir: pulumi_files/src/ol_infrastructure/applications/sign_and_verify
      env:
        AWS_REGION: us-east-1
