---
jobs:
- name: pulumi-stuff-and-things
  plan:
  - get: pulumi_files
    params:
      depth: 1
    trigger: true
  - params:
      action: update
      env:
        AWS_REGION: us-east-1
      project_name: ol-infrastructure-sign-and-verify-application
      source_dir: pulumi_files/src/ol_infrastructure/applications/sign_and_verify
      stack_name: applications.sign_and_verify.QA
    put: pulumi-thing-doer
resource_types:
- name: pulumi
  source:
    repository: mitodl/concourse-pulumi-resource-provisioner
    tag: latest
  type: docker-image
resources:
- icon: github
  name: pulumi_files
  source:
    branch: main
    paths:
    - src/ol_infrastructure/applications/sign_and_verify
    uri: https://github.com/mitodl/ol-infrastructure
  type: git
- name: pulumi-thing-doer
  type: pulumi
